const FLOAT_BYTES = Float32Array.BYTES_PER_ELEMENT;
const VEC4_FLOATS = 4;
const MAT3_COLUMNS = 3;
const PADDED_MAT3_FLOATS = MAT3_COLUMNS * VEC4_FLOATS;

export const FRAME_UNIFORM_SIZE_2D = PADDED_MAT3_FLOATS * FLOAT_BYTES;
export const OBJECT_UNIFORM_SIZE_2D =
  (PADDED_MAT3_FLOATS + VEC4_FLOATS) * FLOAT_BYTES;

export const OBJECT_UNIFORM_OFFSET_2D = Object.freeze({
  transform: 0,
  color: PADDED_MAT3_FLOATS,
});
